#include "irq/interrupts.h"

.macro irq_generic_handler label
.align 7
	irq_save_state
	mov		x0, #\label
	mrs		x1, esr_el1
	mrs 	x2, elr_el1
	bl	 	irq_handle
	irq_restore_state
	eret
.endm

.macro	irq_save_state
	stp x0, x1, [sp, #-16]!
	stp x2, x3, [sp, #-16]!
	stp x4, x5, [sp, #-16]!
	stp x6, x7, [sp, #-16]!
	stp x8, x9, [sp, #-16]!
	stp x10, x11, [sp, #-16]!
	stp x12, x13, [sp, #-16]!
	stp x14, x15, [sp, #-16]!
	stp x16, x17, [sp, #-16]!
	stp x18, x19, [sp, #-16]!
	stp x20, x21, [sp, #-16]!
	stp x22, x23, [sp, #-16]!
	stp x24, x25, [sp, #-16]!
	stp x26, x27, [sp, #-16]!
	stp x28, x29, [sp, #-16]!
	str x30, [sp, #-16]!

	stp q0, q1, [sp, #-32]!
    stp q2, q3, [sp, #-32]!
    stp q4, q5, [sp, #-32]!
    stp q6, q7, [sp, #-32]!
    stp q8, q9, [sp, #-32]!
    stp q10, q11, [sp, #-32]!
    stp q12, q13, [sp, #-32]!
    stp q14, q15, [sp, #-32]!
    stp q16, q17, [sp, #-32]!
    stp q18, q19, [sp, #-32]!
    stp q20, q21, [sp, #-32]!
    stp q22, q23, [sp, #-32]!
    stp q24, q25, [sp, #-32]!
    stp q26, q27, [sp, #-32]!
    stp q28, q29, [sp, #-32]!
    stp q30, q31, [sp, #-32]!

    mrs x0, FPCR
    mrs x1, FPSR
    str x0, [sp, #-16]!
    str x1, [sp, #-16]!
.endm

.macro	irq_restore_state
	ldr x0,  [sp, #16]!
    ldr x1,  [sp, #16]!
    msr FPCR, x0
    msr FPSR, x1

    ldp q30, q31, [sp, #32]!
    ldp q28, q29, [sp, #32]!
    ldp q26, q27, [sp, #32]!
    ldp q24, q25, [sp, #32]!
    ldp q22, q23, [sp, #32]!
    ldp q20, q21, [sp, #32]!
    ldp q18, q19, [sp, #32]!
    ldp q16, q17, [sp, #32]!
    ldp q14, q15, [sp, #32]!
    ldp q12, q13, [sp, #32]!
    ldp q10, q11, [sp, #32]!
    ldp q8, q9, [sp, #32]!
    ldp q6, q7, [sp, #32]!
    ldp q4, q5, [sp, #32]!
    ldp q2, q3, [sp, #32]!
    ldp q0, q1, [sp, #32]!

	ldr x30, [sp, #16]!
    ldp x28, x29, [sp, #16]!
    ldp x26, x27, [sp, #16]!
    ldp x24, x25, [sp, #16]!
    ldp x22, x23, [sp, #16]!
    ldp x20, x21, [sp, #16]!
    ldp x18, x19, [sp, #16]!
    ldp x16, x17, [sp, #16]!
    ldp x14, x15, [sp, #16]!
    ldp x12, x13, [sp, #16]!
    ldp x10, x11, [sp, #16]!
    ldp x8, x9, [sp, #16]!
    ldp x6, x7, [sp, #16]!
    ldp x4, x5, [sp, #16]!
    ldp x2, x3, [sp, #16]!
    ldp x0, x1, [sp, #16]!
.endm

.align	11
.global irq_handlers
irq_handlers:
	irq_generic_handler		SYNC_EL1t	
	irq_generic_handler		IRQ_EL1t
	irq_generic_handler		FIQ_EL1t
	irq_generic_handler		ERROR_EL1t

	irq_generic_handler		SYNC_EL1h
	irq_generic_handler		IRQ_EL1h
	irq_generic_handler		FIQ_EL1h
	irq_generic_handler		ERROR_EL1h

	irq_generic_handler		SYNC_EL0_64
	irq_generic_handler		IRQ_EL0_64
	irq_generic_handler		FIQ_EL0_64
	irq_generic_handler		ERROR_EL0_64

	irq_generic_handler		SYNC_EL0_32
	irq_generic_handler		IRQ_EL0_32
	irq_generic_handler		FIQ_EL0_32
	irq_generic_handler		ERROR_EL0_32
